"""baseline current schema

Revision ID: 20260331_0001
Revises: 
Create Date: 2026-03-31 15:19:41.949399
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '20260331_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_points', sa.JSON(), nullable=True),
    sa.Column('factor_breakdown', sa.JSON(), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('published_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('used_web_search', sa.Boolean(), nullable=False),
    sa.Column('web_search_status', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_format', sa.String(length=16), nullable=False),
    sa.Column('anchor_event_id', sa.String(length=36), nullable=True),
    sa.Column('anchor_event_title', sa.String(length=255), nullable=True),
    sa.Column('structured_sources', sa.JSON(), nullable=True),
    sa.Column('web_sources', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_anchor_event_id'), 'analysis_reports', ['anchor_event_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_session_id'), 'analysis_reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_trigger_source'), 'analysis_reports', ['trigger_source'], unique=False)
    op.create_index(op.f('ix_analysis_reports_ts_code'), 'analysis_reports', ['ts_code'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('cache_variant', sa.String(length=32), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('cluster_key', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.Column('evidence_kind', sa.String(length=32), nullable=False),
    sa.Column('macro_topic', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('event_tags', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_analysis_status'), 'news_events', ['analysis_status'], unique=False)
    op.create_index('ix_news_events_batch_id', 'news_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_news_events_cache_variant'), 'news_events', ['cache_variant'], unique=False)
    op.create_index(op.f('ix_news_events_cluster_key'), 'news_events', ['cluster_key'], unique=False)
    op.create_index(op.f('ix_news_events_event_type'), 'news_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_news_events_evidence_kind'), 'news_events', ['evidence_kind'], unique=False)
    op.create_index(op.f('ix_news_events_external_id'), 'news_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_news_events_fetched_at'), 'news_events', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_news_events_macro_topic'), 'news_events', ['macro_topic'], unique=False)
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_events_scope'), 'news_events', ['scope'], unique=False)
    op.create_index('ix_news_events_scope_cache_variant_fetched_at', 'news_events', ['scope', 'cache_variant', 'fetched_at'], unique=False)
    op.create_index('ix_news_events_scope_cluster_key_fetched_at', 'news_events', ['scope', 'cluster_key', 'fetched_at'], unique=False)
    op.create_index('ix_news_events_scope_topic_published_fetched_created', 'news_events', ['scope', 'macro_topic', 'published_at', 'fetched_at', 'created_at'], unique=False)
    op.create_index('ix_news_events_scope_ts_code_cache_variant_fetched_at', 'news_events', ['scope', 'ts_code', 'cache_variant', 'fetched_at'], unique=False)
    op.create_index('ix_news_events_scope_ts_code_published_fetched_created', 'news_events', ['scope', 'ts_code', 'published_at', 'fetched_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_news_events_source_priority'), 'news_events', ['source_priority'], unique=False)
    op.create_index(op.f('ix_news_events_ts_code'), 'news_events', ['ts_code'], unique=False)
    op.create_table('news_fetch_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('cache_variant', sa.String(length=32), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=True),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('row_count_raw', sa.Integer(), nullable=False),
    sa.Column('row_count_mapped', sa.Integer(), nullable=False),
    sa.Column('row_count_persisted', sa.Integer(), nullable=False),
    sa.Column('provider_stats_json', sa.JSON(), nullable=True),
    sa.Column('degrade_reasons_json', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_fetch_batches_cache_variant'), 'news_fetch_batches', ['cache_variant'], unique=False)
    op.create_index(op.f('ix_news_fetch_batches_fetched_at'), 'news_fetch_batches', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_news_fetch_batches_finished_at'), 'news_fetch_batches', ['finished_at'], unique=False)
    op.create_index(op.f('ix_news_fetch_batches_scope'), 'news_fetch_batches', ['scope'], unique=False)
    op.create_index('ix_news_fetch_batches_scope_cache_variant_fetched_at', 'news_fetch_batches', ['scope', 'cache_variant', 'fetched_at'], unique=False)
    op.create_index('ix_news_fetch_batches_scope_ts_code_cache_variant_fetched_at', 'news_fetch_batches', ['scope', 'ts_code', 'cache_variant', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_news_fetch_batches_status'), 'news_fetch_batches', ['status'], unique=False)
    op.create_index('ix_news_fetch_batches_status_finished_at', 'news_fetch_batches', ['status', 'finished_at'], unique=False)
    op.create_index(op.f('ix_news_fetch_batches_trigger_source'), 'news_fetch_batches', ['trigger_source'], unique=False)
    op.create_index('ix_news_fetch_batches_trigger_source_finished_at', 'news_fetch_batches', ['trigger_source', 'finished_at'], unique=False)
    op.create_index(op.f('ix_news_fetch_batches_ts_code'), 'news_fetch_batches', ['ts_code'], unique=False)
    op.create_table('stock_candidate_evidence_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_kind', sa.String(length=32), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_candidate_evidence_cache_evidence_kind'), 'stock_candidate_evidence_cache', ['evidence_kind'], unique=False)
    op.create_index(op.f('ix_stock_candidate_evidence_cache_fetched_at'), 'stock_candidate_evidence_cache', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_stock_candidate_evidence_cache_published_at'), 'stock_candidate_evidence_cache', ['published_at'], unique=False)
    op.create_index(op.f('ix_stock_candidate_evidence_cache_symbol'), 'stock_candidate_evidence_cache', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_candidate_evidence_cache_ts_code'), 'stock_candidate_evidence_cache', ['ts_code'], unique=False)
    op.create_table('stock_instruments',
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('enname', sa.String(length=256), nullable=True),
    sa.Column('cnspell', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=8), nullable=True),
    sa.Column('curr_type', sa.String(length=8), nullable=True),
    sa.Column('list_status', sa.String(length=1), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.Column('is_hs', sa.String(length=1), nullable=True),
    sa.Column('act_name', sa.String(length=128), nullable=True),
    sa.Column('act_ent_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_index(op.f('ix_stock_instruments_exchange'), 'stock_instruments', ['exchange'], unique=False)
    op.create_index(op.f('ix_stock_instruments_is_hs'), 'stock_instruments', ['is_hs'], unique=False)
    op.create_index(op.f('ix_stock_instruments_list_status'), 'stock_instruments', ['list_status'], unique=False)
    op.create_index(op.f('ix_stock_instruments_market'), 'stock_instruments', ['market'], unique=False)
    op.create_index(op.f('ix_stock_instruments_name'), 'stock_instruments', ['name'], unique=False)
    op.create_index(op.f('ix_stock_instruments_symbol'), 'stock_instruments', ['symbol'], unique=False)
    op.create_table('stock_sync_cursors',
    sa.Column('cursor_key', sa.String(length=32), nullable=False),
    sa.Column('cursor_value', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cursor_key')
    )
    op.create_table('stock_trade_calendars',
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('cal_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.String(length=1), nullable=False),
    sa.Column('pretrade_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'cal_date')
    )
    op.create_index(op.f('ix_stock_trade_calendars_is_open'), 'stock_trade_calendars', ['is_open'], unique=False)
    op.create_table('stock_watch_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_watch_snapshots_captured_at'), 'stock_watch_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_stock_watch_snapshots_ts_code'), 'stock_watch_snapshots', ['ts_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_level'), 'users', ['user_level'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('web_source_metadata_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('resolved_title', sa.String(length=512), nullable=True),
    sa.Column('resolved_source', sa.String(length=255), nullable=True),
    sa.Column('resolved_domain', sa.String(length=255), nullable=True),
    sa.Column('resolved_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_status', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_source_metadata_cache_metadata_status'), 'web_source_metadata_cache', ['metadata_status'], unique=False)
    op.create_index(op.f('ix_web_source_metadata_cache_url_hash'), 'web_source_metadata_cache', ['url_hash'], unique=False)
    op.create_table('analysis_event_links',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('anchor_trade_date', sa.Date(), nullable=True),
    sa.Column('window_return_pct', sa.Float(), nullable=True),
    sa.Column('window_volatility', sa.Float(), nullable=True),
    sa.Column('abnormal_volume_ratio', sa.Float(), nullable=True),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('link_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'ts_code')
    )
    op.create_index(op.f('ix_analysis_event_links_ts_code'), 'analysis_event_links', ['ts_code'], unique=False)
    op.create_table('analysis_generation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_key', sa.String(length=256), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('anchor_event_id', sa.String(length=36), nullable=True),
    sa.Column('use_web_search', sa.Boolean(), nullable=False),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('trigger_source_group', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('summary_preview', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_generation_sessions_analysis_key'), 'analysis_generation_sessions', ['analysis_key'], unique=False)
    op.create_index(op.f('ix_analysis_generation_sessions_anchor_event_id'), 'analysis_generation_sessions', ['anchor_event_id'], unique=False)
    op.create_index(op.f('ix_analysis_generation_sessions_status'), 'analysis_generation_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_generation_sessions_trigger_source'), 'analysis_generation_sessions', ['trigger_source'], unique=False)
    op.create_index(op.f('ix_analysis_generation_sessions_trigger_source_group'), 'analysis_generation_sessions', ['trigger_source_group'], unique=False)
    op.create_index(op.f('ix_analysis_generation_sessions_ts_code'), 'analysis_generation_sessions', ['ts_code'], unique=False)
    op.create_index(op.f('ix_analysis_generation_sessions_use_web_search'), 'analysis_generation_sessions', ['use_web_search'], unique=False)
    op.create_table('stock_adj_factors',
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('adj_factor', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ts_code'], ['stock_instruments.ts_code'], ),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_table('stock_daily_snapshots',
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pre_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vol', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turnover_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_mv', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('circ_mv', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ts_code'], ['stock_instruments.ts_code'], ),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_table('stock_kline_bars',
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pre_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vol', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ts_code'], ['stock_instruments.ts_code'], ),
    sa.PrimaryKeyConstraint('ts_code', 'period', 'trade_date')
    )
    op.create_table('user_watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=12), nullable=False),
    sa.Column('hourly_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('web_search_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_hourly_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_daily_analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ts_code', name='uq_user_watchlist')
    )
    op.create_index(op.f('ix_user_watchlist_items_ts_code'), 'user_watchlist_items', ['ts_code'], unique=False)
    op.create_index(op.f('ix_user_watchlist_items_user_id'), 'user_watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_watchlist_items_user_id'), table_name='user_watchlist_items')
    op.drop_index(op.f('ix_user_watchlist_items_ts_code'), table_name='user_watchlist_items')
    op.drop_table('user_watchlist_items')
    op.drop_table('stock_kline_bars')
    op.drop_table('stock_daily_snapshots')
    op.drop_table('stock_adj_factors')
    op.drop_index(op.f('ix_analysis_generation_sessions_use_web_search'), table_name='analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_generation_sessions_ts_code'), table_name='analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_generation_sessions_trigger_source_group'), table_name='analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_generation_sessions_trigger_source'), table_name='analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_generation_sessions_status'), table_name='analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_generation_sessions_anchor_event_id'), table_name='analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_generation_sessions_analysis_key'), table_name='analysis_generation_sessions')
    op.drop_table('analysis_generation_sessions')
    op.drop_index(op.f('ix_analysis_event_links_ts_code'), table_name='analysis_event_links')
    op.drop_table('analysis_event_links')
    op.drop_index(op.f('ix_web_source_metadata_cache_url_hash'), table_name='web_source_metadata_cache')
    op.drop_index(op.f('ix_web_source_metadata_cache_metadata_status'), table_name='web_source_metadata_cache')
    op.drop_table('web_source_metadata_cache')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_level'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_watch_snapshots_ts_code'), table_name='stock_watch_snapshots')
    op.drop_index(op.f('ix_stock_watch_snapshots_captured_at'), table_name='stock_watch_snapshots')
    op.drop_table('stock_watch_snapshots')
    op.drop_index(op.f('ix_stock_trade_calendars_is_open'), table_name='stock_trade_calendars')
    op.drop_table('stock_trade_calendars')
    op.drop_table('stock_sync_cursors')
    op.drop_index(op.f('ix_stock_instruments_symbol'), table_name='stock_instruments')
    op.drop_index(op.f('ix_stock_instruments_name'), table_name='stock_instruments')
    op.drop_index(op.f('ix_stock_instruments_market'), table_name='stock_instruments')
    op.drop_index(op.f('ix_stock_instruments_list_status'), table_name='stock_instruments')
    op.drop_index(op.f('ix_stock_instruments_is_hs'), table_name='stock_instruments')
    op.drop_index(op.f('ix_stock_instruments_exchange'), table_name='stock_instruments')
    op.drop_table('stock_instruments')
    op.drop_index(op.f('ix_stock_candidate_evidence_cache_ts_code'), table_name='stock_candidate_evidence_cache')
    op.drop_index(op.f('ix_stock_candidate_evidence_cache_symbol'), table_name='stock_candidate_evidence_cache')
    op.drop_index(op.f('ix_stock_candidate_evidence_cache_published_at'), table_name='stock_candidate_evidence_cache')
    op.drop_index(op.f('ix_stock_candidate_evidence_cache_fetched_at'), table_name='stock_candidate_evidence_cache')
    op.drop_index(op.f('ix_stock_candidate_evidence_cache_evidence_kind'), table_name='stock_candidate_evidence_cache')
    op.drop_table('stock_candidate_evidence_cache')
    op.drop_index(op.f('ix_news_fetch_batches_ts_code'), table_name='news_fetch_batches')
    op.drop_index('ix_news_fetch_batches_trigger_source_finished_at', table_name='news_fetch_batches')
    op.drop_index(op.f('ix_news_fetch_batches_trigger_source'), table_name='news_fetch_batches')
    op.drop_index('ix_news_fetch_batches_status_finished_at', table_name='news_fetch_batches')
    op.drop_index(op.f('ix_news_fetch_batches_status'), table_name='news_fetch_batches')
    op.drop_index('ix_news_fetch_batches_scope_ts_code_cache_variant_fetched_at', table_name='news_fetch_batches')
    op.drop_index('ix_news_fetch_batches_scope_cache_variant_fetched_at', table_name='news_fetch_batches')
    op.drop_index(op.f('ix_news_fetch_batches_scope'), table_name='news_fetch_batches')
    op.drop_index(op.f('ix_news_fetch_batches_finished_at'), table_name='news_fetch_batches')
    op.drop_index(op.f('ix_news_fetch_batches_fetched_at'), table_name='news_fetch_batches')
    op.drop_index(op.f('ix_news_fetch_batches_cache_variant'), table_name='news_fetch_batches')
    op.drop_table('news_fetch_batches')
    op.drop_index(op.f('ix_news_events_ts_code'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_source_priority'), table_name='news_events')
    op.drop_index('ix_news_events_scope_ts_code_published_fetched_created', table_name='news_events')
    op.drop_index('ix_news_events_scope_ts_code_cache_variant_fetched_at', table_name='news_events')
    op.drop_index('ix_news_events_scope_topic_published_fetched_created', table_name='news_events')
    op.drop_index('ix_news_events_scope_cluster_key_fetched_at', table_name='news_events')
    op.drop_index('ix_news_events_scope_cache_variant_fetched_at', table_name='news_events')
    op.drop_index(op.f('ix_news_events_scope'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_macro_topic'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_fetched_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_external_id'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_evidence_kind'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_event_type'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_cluster_key'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_cache_variant'), table_name='news_events')
    op.drop_index('ix_news_events_batch_id', table_name='news_events')
    op.drop_index(op.f('ix_news_events_analysis_status'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_analysis_reports_ts_code'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_trigger_source'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_session_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_anchor_event_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
